import fs from "node:fs";
import path from "node:path";

const pycallRbPath = path.resolve("lib/pycall.rb");
const errorRbPath = path.resolve("lib/pycall/error.rb");
const importRbPath = path.resolve("lib/pycall/import.rb");
const numpyRbPath = path.resolve("lib/numpy.rb");
const numpyNdarrayRbPath = path.resolve("lib/numpy/ndarray.rb");
const outputPath = path.resolve("src/ruby_code.ts");

const pycallRb = fs.readFileSync(pycallRbPath, "utf-8");
const errorRb = fs.readFileSync(errorRbPath, "utf-8");
const importRb = fs.readFileSync(importRbPath, "utf-8");
const numpyRb = fs.readFileSync(numpyRbPath, "utf-8");
const numpyNdarrayRb = fs.readFileSync(numpyNdarrayRbPath, "utf-8");

// Ensure src directory exists
if (!fs.existsSync(path.dirname(outputPath))) {
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
}

const content = `// This file is auto-generated by scripts/embed_ruby.js. Do not edit directly.
export const pycallRb = ${JSON.stringify(pycallRb)};
export const errorRb = ${JSON.stringify(errorRb)};
export const importRb = ${JSON.stringify(importRb)};
export const numpyRb = ${JSON.stringify(numpyRb)};
export const numpyNdarrayRb = ${JSON.stringify(numpyNdarrayRb)};
`;

fs.writeFileSync(outputPath, content, "utf-8");
console.log("Embedded Ruby source files into src/ruby_code.ts successfully.");
